
version: "3.7"
services:
  scraping:
    build:
      context: .
    image: 705373246515.dkr.ecr.ap-northeast-2.amazonaws.com/scraping:0.0.2
    ports:
      - 8080:8080
    command:
      ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    environment:
      # KAFKA_HOST: a0cf6638ed1d24e16b0086f395e8bb90-1437709784.ap-northeast-2.elb.amazonaws.com
      KAFKA_HOST: kafka.eevllab.studio
      KAFKA_PORT: 9092
      REDIS_HOST: 1
      REDIS_PORT: 1
      REDIS_DB_NUM: 1
    volumes:
      - .:/app