
version: "3.7"
services:
  scraping:
    build:
      context: .
    image: 705373246515.dkr.ecr.ap-northeast-2.amazonaws.com/scraping:0.2.1
    ports:
      - 8080:8080
    command:
      ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    environment:
      KAFKA_BROKER_0: kafka-0.kafka-headless.kafka.svc.cluster.local:9092
      KAFKA_BROKER_1: kafka-1.kafka-headless.kafka.svc.cluster.local:9092
      KAFKA_BROKER_2: kafka-2.kafka-headless.kafka.svc.cluster.local:9092
      REDIS_HOST: 1
      REDIS_PORT: 1
      REDIS_DB_NUM: 1
    volumes:
      - .:/app