
version: "3.7"
services:
  scraping:
    build:
      context: .
    image: scraping:0.0.1
    ports:
      - 8080:8080
    command:
      ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    environment:
      TZ: UTC
    volumes:
      - .:/app